import {useState} from 'react'; import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'; import {Link,Route,Routes,useLocation,useParams} from 'react-router-dom';
import {Activity,AlertTriangle,ArrowUpRight,BadgeCheck,Banknote,BarChart3,Bell,ChevronRight,Download,FileSearch,LayoutDashboard,Menu,Moon,Search,Settings,ShieldAlert,Sun,UploadCloud,Users,X} from 'lucide-react';
import {Area,AreaChart,Bar,BarChart,CartesianGrid,Cell,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts'; import {api,Application} from './api';
const money=(v:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v);
const statusClass=(s:string)=>`badge ${s.toLowerCase()}`;

function Shell({children}:{children:React.ReactNode}){const loc=useLocation();const [dark,setDark]=useState(false);const links=[["/",LayoutDashboard,"Overview"],["/applications",FileSearch,"Applications"],["/upload",UploadCloud,"Upload & Analyze"],["/analytics",BarChart3,"Analytics"]] as const;return <div className={dark?'app dark':'app'}><aside><div className="brand"><span><Banknote/></span><div>LoanLens<small>Decision Intelligence</small></div></div><nav>{links.map(([to,Icon,label])=><Link className={(loc.pathname===to)?'active':''} to={to}><Icon/>{label}</Link>)}</nav><div className="side-foot"><div className="avatar">GR</div><div><b>Gayathri R.</b><small>Senior Loan Officer</small></div><Settings/></div></aside><main><header><button className="mobile"><Menu/></button><div className="search"><Search/><input placeholder="Search applications, customers..."/></div><button className="icon" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button><button className="icon"><Bell/></button></header>{children}</main></div>}

function Metric({icon:Icon,label,value,detail,tone}:{icon:any,label:string,value:string|number,detail:string,tone:string}){return <div className="metric"><div className={`metric-icon ${tone}`}><Icon/></div><div><p>{label}</p><h2>{value}</h2><small>{detail}</small></div></div>}
function Dashboard(){const {data:d}=useQuery({queryKey:['dashboard'],queryFn:async()=>(await api.get('/dashboard')).data});if(!d)return <Loading/>;const status=Object.entries(d.status_distribution).map(([name,value])=>({name,value}));return <div className="page"><Title eyebrow="TUESDAY, 14 JULY" title="Good morning, Gayathri" subtitle="Here’s what’s happening across your loan portfolio."/><div className="metrics"><Metric icon={FileSearch} label="Total applications" value={d.total_applications} detail="All processed cases" tone="blue"/><Metric icon={BadgeCheck} label="Approved loans" value={d.approved} detail="Strong credit profiles" tone="green"/><Metric icon={Activity} label="Pending review" value={d.pending} detail="Require officer action" tone="amber"/><Metric icon={ShieldAlert} label="Fraud alerts" value={d.fraud_alerts} detail="High attention signals" tone="red"/></div><div className="grid-charts"><section className="card wide"><CardTitle title="Application volume" sub="Monthly processing trend"/><ResponsiveContainer width="100%" height={250}><AreaChart data={d.monthly}><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#2857d7" stopOpacity=".3"/><stop offset="1" stopColor="#2857d7" stopOpacity="0"/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month"/><YAxis/><Tooltip/><Area type="monotone" dataKey="applications" stroke="#2857d7" fill="url(#g)" strokeWidth={3}/></AreaChart></ResponsiveContainer></section><section className="card"><CardTitle title="Decision mix" sub="Current portfolio"/><ResponsiveContainer width="100%" height={210}><PieChart><Pie data={status} innerRadius={55} outerRadius={82} dataKey="value" paddingAngle={4}>{status.map((_:any,i:number)=><Cell fill={['#23a36d','#e6a127','#df4b56'][i]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div className="legend">{status.map((x:any)=><span><i/>{x.name} <b>{x.value}</b></span>)}</div></section></div><Recent rows={d.recent}/></div>}
function Title({eyebrow,title,subtitle,action}:{eyebrow?:string,title:string,subtitle:string,action?:React.ReactNode}){return <div className="title"><div>{eyebrow&&<small>{eyebrow}</small>}<h1>{title}</h1><p>{subtitle}</p></div>{action}</div>}
function CardTitle({title,sub}:{title:string;sub:string}){return <div className="card-title"><div><h3>{title}</h3><p>{sub}</p></div><button className="dots">•••</button></div>}
function Recent({rows}:{rows:Application[]}){return <section className="card table-card"><CardTitle title="Recent applications" sub="Latest applications analyzed by LoanLens AI"/><table><thead><tr><th>Applicant</th><th>Loan</th><th>Amount</th><th>Risk</th><th>Fraud</th><th>Decision</th><th></th></tr></thead><tbody>{rows.map(x=><tr><td><b>{x.applicant_name}</b><small>{x.id}</small></td><td>{x.loan_type}</td><td>{money(x.loan_amount)}</td><td><Score value={x.risk_score}/></td><td><Score value={x.fraud_score}/></td><td><span className={statusClass(x.status)}>{x.status}</span></td><td><Link to={`/applications/${x.id}`}><ChevronRight/></Link></td></tr>)}</tbody></table></section>}
function Score({value}:{value:number}){return <span className="score"><i style={{width:`${value}%`}} className={value>69?'high':value>39?'mid':'low'}/><b>{value.toFixed(0)}</b></span>}
function Applications(){const {data=[]}=useQuery<Application[]>({queryKey:['applications'],queryFn:async()=>(await api.get('/applications')).data});return <div className="page"><Title title="Loan applications" subtitle="Review every application and its AI-assisted decision." action={<Link className="primary" to="/upload"><UploadCloud/>Upload data</Link>}/><Recent rows={data}/></div>}
function Upload(){
 const qc=useQueryClient(); const [files,setFiles]=useState<File[]>([]); const [applicantName,setApplicantName]=useState(''); const [loanType,setLoanType]=useState('Personal Loan');
 const mut=useMutation({mutationFn:async()=>{const form=new FormData();files.forEach(file=>form.append('files',file));form.append('applicant_name',applicantName.trim());form.append('loan_type',loanType);return (await api.post('/upload',form)).data},onSuccess:()=>qc.invalidateQueries()});
 const addFiles=(incoming:FileList|null)=>{if(!incoming)return;setFiles(current=>Array.from(new Map([...current,...Array.from(incoming)].map(file=>[`${file.name}-${file.size}`,file])).values()).slice(0,25))};
 return <div className="page narrow"><Title title="Upload & analyze" subtitle="Analyze a complete applicant pack or multiple application files in one batch."/><section className="card upload"><div className="upload-icon"><UploadCloud/></div><h2>Upload multiple loan documents</h2><p>First identify the loan seeker, then attach up to 25 supporting documents.</p><div className="upload-fields"><label><span>Loan seeker name</span><input value={applicantName} maxLength={160} placeholder="e.g. Priya Sharma" onChange={e=>setApplicantName(e.target.value)}/></label><label><span>Type of loan</span><select value={loanType} onChange={e=>setLoanType(e.target.value)}>{['Personal Loan','Home Loan','Car Loan','Education Loan','Business Loan','Gold Loan'].map(type=><option key={type}>{type}</option>)}</select></label></div><div className="file-help">CSV, Excel, PDF or JSON · maximum 1,000 records per structured file</div><label className="primary">Choose files<input multiple type="file" accept=".csv,.xlsx,.xls,.pdf,.json" onChange={e=>{addFiles(e.target.files);e.target.value='' }}/></label>
 {files.length>0&&<div className="file-list">{files.map((file,index)=><div className="chosen" key={`${file.name}-${file.size}`}><FileSearch/><div><b>{file.name}</b><small>{(file.size/1024).toFixed(1)} KB · ready to analyze</small></div><button aria-label={`Remove ${file.name}`} onClick={()=>setFiles(items=>items.filter((_,i)=>i!==index))}><X/></button></div>)}</div>}
 <button className="analyze" disabled={!files.length||applicantName.trim().length<2||mut.isPending} onClick={()=>mut.mutate()}>{mut.isPending?`Analyzing ${files.length} files…`:`Analyze ${files.length} file${files.length===1?'':'s'} for ${applicantName.trim()||'applicant'}`}<ArrowUpRight/></button>
 {mut.isSuccess&&<div className="batch-result"><div className="success"><BadgeCheck/><div><b>Batch analysis complete</b><p>{mut.data.created} applications created from {mut.data.files_analyzed} of {mut.data.files_received} files · {mut.data.duplicates_skipped} duplicates skipped</p></div></div>{mut.data.results.map((result:any)=><div className={`file-result ${result.status}`} key={result.filename}><FileSearch/><b>{result.filename}</b><span>{result.status==='analyzed'?`${result.records} record${result.records===1?'':'s'} analyzed`:result.error}</span></div>)}</div>}
 {mut.isError&&<div className="error">No applications could be extracted. Review the file formats and try again.</div>}</section><div className="steps">{['Validate & clean','Extract fields','Detect anomalies','Score & recommend'].map((x,i)=><div><span>{i+1}</span><b>{x}</b><small>{['Schema checks and deduplication','Normalize applicant financials','Fraud and sentiment signals','Explainable loan decision'][i]}</small></div>)}</div></div>}
function Detail(){const {id}=useParams();const {data:x}=useQuery<Application>({queryKey:['application',id],queryFn:async()=>(await api.get(`/applications/${id}`)).data});if(!x)return <Loading/>;return <div className="page"><Title title={x.applicant_name} subtitle={`${x.id} · received ${new Date(x.created_at).toLocaleDateString('en-IN')}`} action={<a className="secondary" href={`${api.defaults.baseURL}/reports/applications.csv`}><Download/>Download report</a>}/><div className="detail-grid"><section className="card profile"><h3>Applicant profile</h3><dl><div><dt>Annual income</dt><dd>{money(x.income)}</dd></div><div><dt>Requested amount</dt><dd>{money(x.loan_amount)}</dd></div><div><dt>Credit score</dt><dd>{x.credit_score}</dd></div><div><dt>Debt-to-income</dt><dd>{x.dti.toFixed(1)}%</dd></div><div><dt>Employment</dt><dd>{x.employment_years} years</dd></div><div><dt>Sentiment</dt><dd><span className="badge neutral">{x.sentiment} · {(x.sentiment_confidence*100).toFixed(0)}%</span></dd></div></dl></section><section className="card decision"><span>AI RECOMMENDATION</span><h2 className={x.status.toLowerCase()}>{x.status}</h2><p>{x.ai_summary}</p><div className="gauges"><div><b>{x.risk_score.toFixed(0)}</b><small>Risk score</small></div><div><b>{x.fraud_score.toFixed(0)}</b><small>Fraud score</small></div></div></section><section className="card reasoning"><h3>Decision reasoning</h3><p>{x.explanation}</p><h4>Processing trail</h4>{x.processing_log.map(t=><div className="log"><BadgeCheck/>{t}</div>)}</section></div></div>}
function Analytics(){const {data}=useQuery({queryKey:['analytics'],queryFn:async()=>(await api.get('/analytics')).data});if(!data)return <Loading/>;const chart=(o:any)=>Object.entries(o).map(([name,value])=>({name,value}));return <div className="page"><Title title="Portfolio analytics" subtitle="Understand risk, fraud and customer sentiment across the lending funnel." action={<a className="secondary" href={`${api.defaults.baseURL}/reports/applications.csv`}><Download/>Export CSV</a>}/><div className="analytics-grid">{[['Risk categories',data.risk],['Fraud distribution',data.fraud],['Sentiment analysis',data.sentiment]].map(([title,d]:any)=><section className="card"><CardTitle title={title} sub="Analyzed applications"/><ResponsiveContainer width="100%" height={260}><BarChart data={chart(d)}><CartesianGrid vertical={false}/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="value" fill="#2857d7" radius={[7,7,0,0]}/></BarChart></ResponsiveContainer></section>)}</div></div>}
function Loading(){return <div className="loading"><span/>Loading intelligence…</div>}
export default function App(){return <Shell><Routes><Route path="/" element={<Dashboard/>}/><Route path="/applications" element={<Applications/>}/><Route path="/applications/:id" element={<Detail/>}/><Route path="/upload" element={<Upload/>}/><Route path="/analytics" element={<Analytics/>}/></Routes></Shell>}
